### ISSUE TITLE
IP可以访问呢,域名却不能访问,用腾讯云解析检测可以检测成功.

### ISSUE THREAD

**Issue by MQL9011** [wsydxiangwang/Mood#9]
折腾了好久还是不行
IP可以正常访问
域名就是不行,不知道自己哪里没配置好,好心烦

**Comment by wsydxiangwang** [comment]
域名访问显示什么？？

IP可以正常访问，那就只有这两个问题了。
- 部署的第二步，文件（nginx.conf）有没有填写你需要的域名？？
- 如有，那就是域名解析，没有解析到对应的服务器IP，或者解析错误？？

自己学学找问题吧，不懂就百度。。。
